apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ipgrabber-
spec:
  serviceAccountName: pod-info-sa
  entrypoint: ipgrabber-job
  templates:
    - name: ipgrabber-job
      container:
        image: projectred521/ipgrabber:latest
