apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tsunami-docker-workflow-
spec:
  entrypoint: start
  templates:
    - name: start
      steps:
        - - name: run-java-command
            template: run-command

    - name: run-command
      container:
        image: projectred521/tsunami:v0.1.0
        command: ["/bin/sh"]
        args:
          - -c
          - |
            java -cp "tsunami.jar:plugins/*" \
            -Dtsunami-config.location=tsunami.yaml \
            com.google.tsunami.main.cli.TsunamiCli \
            --ip-v4-target=10.244.0.142 \
            --scan-results-local-output-format=JSON \
            --scan-results-local-output-filename=tsunami-output.json
            cat tsunami-output.json

